# Generated by Django 4.2.7 on 2023-11-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='curiosidade',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
