# Generated by Django 4.2.7 on 2023-11-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flower_curiosidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='curiosidade',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='flower',
            name='especie',
            field=models.CharField(max_length=255),
        ),
    ]
